// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ftJTi0IWKpRa8ldkcQU_gY22p3Ak1SA',
    appId: '1:555974284451:web:9245df39afde81c7789b16',
    messagingSenderId: '555974284451',
    projectId: 'betting-a15c3',
    authDomain: 'betting-a15c3.firebaseapp.com',
    storageBucket: 'betting-a15c3.appspot.com',
    measurementId: 'G-KXGTGJ0TBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyQGVfriiQd19Ndp5Uc4SbF2wO4gUK-E',
    appId: '1:555974284451:android:e569657105f496e6789b16',
    messagingSenderId: '555974284451',
    projectId: 'betting-a15c3',
    storageBucket: 'betting-a15c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhrkUocR9iR4W7jlMWBd1AzcDrf9_jdU',
    appId: '1:555974284451:ios:244f1d8023ec19a3789b16',
    messagingSenderId: '555974284451',
    projectId: 'betting-a15c3',
    storageBucket: 'betting-a15c3.appspot.com',
    iosClientId: '555974284451-v1m09b6tof90laloco9jvng4t6vk4d21.apps.googleusercontent.com',
    iosBundleId: 'com.example.betingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVhrkUocR9iR4W7jlMWBd1AzcDrf9_jdU',
    appId: '1:555974284451:ios:244f1d8023ec19a3789b16',
    messagingSenderId: '555974284451',
    projectId: 'betting-a15c3',
    storageBucket: 'betting-a15c3.appspot.com',
    iosClientId: '555974284451-v1m09b6tof90laloco9jvng4t6vk4d21.apps.googleusercontent.com',
    iosBundleId: 'com.example.betingApp',
  );
}
